### PR TITLE
DRAFT: resolve-mixed-media-content-error

### PR DESCRIPTION
**Pull request by aprilrieger**
Ref ticket:
Issue with being able to see items in the UV viewer. Since the site is setup up with config.force_ssl = false due to site dns configuration with this client. We need to set the iiif base_url to change them in the manifest to https to fix the mixed media content issue we are currently seeing on production.

### CODE REVIEW

**Comment by aprilrieger** [comment]
After reviewing the info she gave me and looking at Atla’s code I have determined there is more lift here due the code from the example being hyrax 2.9.0 as well as Hyku with the utilization of the ssl_configured? method that is specific to our multitenancy on hyku, and having a class IiifManifestPresenter, whereas Atla DL is clocked at hyrax 2.6.0 and does not have a IiifManifestPresenter.

**Comment by aprilrieger** [comment]
After reviewing the info she given to me and looking at Atla’s code I have determined there is more lift here due the code from the example being hyrax 2.9.0 as well as Hyku with the utilization of the ssl_configured? method that is specific to our multitenancy on hyku, and having a class IiifManifestPresenter, whereas Atla DL is clocked at hyrax 2.6.0 and does not have a IiifManifestPresenter.

**Comment by ShanaLMoore** [comment]
This shouldn't require a reindex.

**Comment by aprilrieger** [comment]
closing as this got fixed through the loadbalancer upgrade

**Pull request closed without merging**
